'use strict';
// Self-contained WebGL scene: actual depth-tested 3D meshes, no remote dependencies.
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tasks=[{name:'找到原始單據',place:'材料進場區',pos:[-5,2,4.1],guide:'先去材料進場區，找到能證明「實際交貨量」的資料。'},{name:'核對數量單位',place:'資料蒐集站',pos:[-5,3,-4.4],guide:'送貨單的 9.0 是什麼單位？把活動數據連同單位一起記下。'},{name:'修正申報落差',place:'資料檢核室',pos:[4.7,3,-4.2],guide:'申報表和原始單據不一致！先找差異，再留下修正紀錄。'},{name:'完成查證交接',place:'查證集合點',pos:[5.2,2.3,3.9],guide:'把原始單據、修正版申報表與差異說明串起來，交給查證人員。'}];
let state={done:0,mistakes:0,started:Date.now(),finished:null}, saved;
try{saved=JSON.parse(localStorage.getItem('carbon-field-v1'));if(saved&&Number.isInteger(saved.done)&&saved.done>=0&&saved.done<=4&&Number.isInteger(saved.mistakes)&&saved.mistakes>=0&&Number.isFinite(saved.started))state=saved;}catch(e){}
let active=-1, lastFocus=null, toastTimer, target=[-1,0,4.7], avatar=[-1,0,4.7];
function save(){try{localStorage.setItem('carbon-field-v1',JSON.stringify(state));}catch(e){}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function update(){
 $('#counter').textContent=`${state.done} / 4 完成`;$('#bar').style.width=state.done*25+'%';$('#guideText').textContent=state.done===4?'做得好！資料有來源、修正有紀錄，現在可以開啟查證成果。':tasks[state.done].guide;
 $('#missions').innerHTML=tasks.map((t,i)=>`<button class="mission ${i<state.done?'done':i===state.done?'current':''}" data-task="${i}" ${i===state.done?'aria-current="step"':''}><span class="num">${i<state.done?'✓':String(i+1).padStart(2,'0')}</span><span><b>${t.name}</b><small>${t.place}</small></span><span class="arrow">↗</span></button>`).join('');
 $$('.mission').forEach(b=>b.onclick=()=>visit(+b.dataset.task));
 $$('.pin').forEach((b,i)=>{b.className='pin '+(i<state.done?'done':i===state.done?'active':'');b.innerHTML=`<em>${i<state.done?'✓':String(i+1).padStart(2,'0')}</em>${tasks[i].place}`;});
}
function openDialog(html){lastFocus=document.activeElement;$('#dialogContent').innerHTML=html;$('#modal').hidden=false;$('header').inert=true;$('main').inert=true;$('.dialog').scrollTop=0;$('.dialog').focus();}
function closeDialog(){$('#modal').hidden=true;$('header').inert=false;$('main').inert=false;active=-1;if(lastFocus&&document.contains(lastFocus))lastFocus.focus();}
$('#close').onclick=closeDialog;
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeDialog();});
document.addEventListener('keydown',e=>{
 if(!$('#modal').hidden){if(e.key==='Escape')closeDialog();if(e.key==='Tab'){const f=$$('.dialog button,.dialog input,.dialog select,.dialog a').filter(x=>!x.disabled);const a=f[0],b=f[f.length-1];if(e.shiftKey&&(document.activeElement===a||document.activeElement===$('.dialog'))){e.preventDefault();b.focus();}else if(!e.shiftKey&&(document.activeElement===b||document.activeElement===$('.dialog'))){e.preventDefault();a.focus();}}return;}
 if(/^[1-4]$/.test(e.key))visit(+e.key-1);
 if(e.key==='ArrowLeft'){e.preventDefault();yaw-=.15;}if(e.key==='ArrowRight'){e.preventDefault();yaw+=.15;}if(e.key==='+'||e.key==='=')setZoom(-1);if(e.key==='-')setZoom(1);
});
const ticket=()=>`<article class="ticket"><div class="ticket-label">TRAINING EVIDENCE / 01</div><h3>預拌混凝土送貨單</h3><dl><div><dt>練習編號</dt><dd>DEMO-001</dd></div><div><dt>材料</dt><dd>預拌混凝土</dd></div><div><dt>交貨數量</dt><dd class="qty">9.0 <small>m³</small></dd></div><div><dt>收料狀態</dt><dd>已簽收 · 本期交貨</dd></div></dl><footer>教育情境重建。9.0 m³ 延續影片案例；編號與收料狀態為遊戲假設，並非真實單據的額外查核結果。</footer></article>`;
function visit(i){if(i>state.done){toast(`先完成第 ${state.done+1} 個任務，小綠就會帶你前往下一站。`);return;}target=[tasks[i].pos[0]+1.6,0,tasks[i].pos[2]+1.9];active=i;if(state.done===4){showResults();return;}if(i<state.done){openDialog(`<div class="eyebrow">任務 ${i+1} · 已完成</div><h2 id="dialogTitle">${tasks[i].name} ✓</h2><p class="sub">${['原始送貨單能支持實際交貨量；採購需求與預估報價不等於實際進場。','本案例的活動數據是 9.0 m³。體積與重量不同，不能把 m³ 直接改寫成 t。','保留原始單據，將申報的 90.0 m³ 修正為 9.0 m³，並留下原因與修正紀錄。','用原始單據、修正後申報表與差異說明建立可追溯的資料鏈。'][i]}</p><button class="primary" id="back">回到工地</button>`);$('#back').onclick=closeDialog;return;}
 let content='';
 if(i===0)content=`<div class="task-layout"><div class="ledger" style="align-self:start"><div class="eyebrow">現場線索</div><h3>混凝土車抵達工地</h3><p>今天有一車混凝土完成交貨。你要蒐集能支持「實際進場數量」的資料。</p><p>桌上有三份文件，先選出最直接的依據。</p></div><div class="options"><button class="option" data-answer="order"><b>採購需求單 · 90 m³</b><span>規劃整個工區的預計用量</span></button><button class="option" data-answer="ticket"><b>已簽收送貨單 · 9.0 m³</b><span>記錄這次實際交貨數量</span></button><button class="option" data-answer="quote"><b>廠商報價單 · 10 m³</b><span>報價估算，尚未代表交貨</span></button></div></div>`;
 if(i===1)content=`<div class="task-layout">${ticket()}<form id="entry"><label class="field">交貨數量<input name="quantity" type="number" inputmode="decimal" min="0" step="0.1" placeholder="輸入單據上的數量" required></label><label class="field">原始單位<select name="unit" required><option value="">選擇單位</option><option value="t">t · 公噸（重量）</option><option value="m3">m³ · 立方公尺（體積）</option><option value="kg">kg · 公斤（重量）</option></select></label><button class="primary" type="submit">確認這筆資料 →</button></form></div>`;
 if(i===2)content=`<div class="task-layout">${ticket()}<div><div class="ledger">申報表目前填寫<br><strong style="color:#aa653d">90.0 m³</strong><br>原始送貨單卻是 9.0 m³。怎麼處理？</div><div class="options"><button class="option" data-answer="source"><b>把送貨單改成 90.0 m³</b><span>讓文件看起來一致</span></button><button class="option" data-answer="correct"><b>申報改為 9.0 m³，保留修正紀錄</b><span>保留原始單據，說明誤植原因</span></button><button class="option" data-answer="ignore"><b>先保留 90.0 m³ 直接送出</b><span>之後再看看是否有人詢問</span></button></div></div></div>`;
 if(i===3)content=`<div class="task-layout"><div class="ledger" style="align-self:start"><div class="eyebrow">查證人員提問</div><h3>「這筆 9.0 m³ 從哪裡來？」</h3><p>「為什麼申報曾是 90.0？<br>誰能說明這次修正？」</p><p>選出本次交接需要的三份資料，讓查證人員能追溯來源與變更。</p></div><form id="packet"><div class="options"><label class="check"><input type="checkbox" name="doc" value="ticket">原始已簽收送貨單（9.0 m³）</label><label class="check"><input type="checkbox" name="doc" value="register">修正後申報表（9.0 m³）</label><label class="check"><input type="checkbox" name="doc" value="memo">差異說明與修正紀錄（含權責人）</label><label class="check"><input type="checkbox" name="doc" value="photo">無日期、無單據編號的工地照片</label><label class="check"><input type="checkbox" name="doc" value="quote">尚未交貨的 10 m³ 報價單</label></div><button class="primary" style="margin-top:18px" type="submit">送出查證資料包 →</button></form></div>`;
 openDialog(`<div class="eyebrow">任務 ${String(i+1).padStart(2,'0')} / 04 · ${tasks[i].place}</div><h2 id="dialogTitle">${tasks[i].name}</h2><p class="sub">${['選擇最能證明這次實際交貨量的文件。','從單據讀出數值，連同正確單位一起記錄。','資料不一致時，以原始佐證確認事實，保留修正軌跡。','點選三份必要資料，再送出。'][i]}</p>${content}<div id="feedback" class="feedback" role="status" aria-live="polite"></div><div class="actions" id="nextAction"></div>`);
 $$('[data-answer]').forEach(b=>b.onclick=()=>{let ok=i===0?b.dataset.answer==='ticket':b.dataset.answer==='correct';if(ok)complete(i);else wrong(i===0?'這份文件反映預計需求或報價，不能直接代表這車實際交貨量。請找有交貨與簽收紀錄的單據。':'不能修改原始佐證來配合錯誤申報，也不能忽略差異。請修正申報，保留原始單據與修正紀錄。');});
 if(i===1)$('#entry').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);if(Number(d.get('quantity'))===9&&d.get('unit')==='m3')complete(i);else wrong('再看送貨單：9.0 的單位是 m³（體積）。本練習沒有密度資料，不可直接改寫為公噸或公斤。');};
 if(i===3)$('#packet').onsubmit=e=>{e.preventDefault();const v=new FormData(e.target).getAll('doc');if(v.length===3&&['ticket','register','memo'].every(x=>v.includes(x)))complete(i);else wrong('需要「原始單據＋修正後申報表＋修正說明」。無法連結本次交貨的照片或未交貨報價，不能取代這條資料鏈。');};
}
function wrong(s){state.mistakes++;save();$('#feedback').className='feedback';$('#feedback').textContent='再試一次｜'+s;}
function complete(i){if(state.done!==i)return;state.done++;if(state.done===4)state.finished=Date.now();save();update();$('#feedback').className='feedback good';$('#feedback').textContent=['✓ 找到了！送貨單支持實際交貨，數據的來源要跟著保存。','✓ 正確！本次活動數據是 9.0 m³；這是交貨體積，並非碳排放量。','✓ 差異已處理：90.0 → 9.0 m³。原始佐證保留，修正原因與權責人需記錄。','✓ 資料链完整！來源、申報與修正說明都能互相對照。'][i].replace('资料','資料').replace('链','鏈');
 $$('#dialogContent .option,#dialogContent input,#dialogContent select,#dialogContent form button').forEach(b=>b.disabled=true);
 $('#nextAction').innerHTML=`<button class="primary" id="next">${i===3?'查看查證成果 →':'前往下一站 →'}</button>`;$('#next').onclick=()=>{closeDialog();if(i===3)showResults();else{target=[tasks[i+1].pos[0]+1.5,0,tasks[i+1].pos[2]+1.5];toast(`下一站：${tasks[i+1].place}。點選地標開始。`);}};$('#next').focus();
}
function showResults(){openDialog(`<div class="results"><div class="success-icon">✓</div><div class="eyebrow" style="justify-content:center">MISSION COMPLETE / 查證任務完成</div><h2 id="dialogTitle">每一筆數據，都有跡可循。</h2><p class="sub">你已完成混凝土活動數據的蒐集、核對、修正與交接。</p><div class="result-grid"><div><b>4 / 4</b><span>完成任務</span></div><div><b>9.0 m³</b><span>核對後活動數據</span></div><div><b>3 份</b><span>完整交接資料</span></div></div><div class="result-list">✓ 找到原始送貨單，區分實際交貨與預估數量。<br>✓ 保留正確數值及單位，不把體積直接當重量。<br>✓ 修正 90.0 → 9.0 m³，並保留來源與修正紀錄。<br>✓ 以原始單據、修正後申報表、差異說明完成交接。</div><p class="sub" style="margin:18px 0 0">本遊戲練習的是活動數據與查證資料鏈，尚未計算碳排放量。<br>情境為教育模擬，不能作為正式盤查或查證結論。</p><div class="actions" style="justify-content:center"><button class="secondary" id="replay">再玩一次</button><button class="primary" id="download">下載學習紀錄 ↓</button></div></div>`);$('#replay').onclick=confirmReset;$('#download').onclick=download;}
function download(){const data=`小綠的碳盤查任務｜學習紀錄\n完成：${new Date(state.finished||Date.now()).toLocaleString('zh-TW')}\n任務：4 / 4\n活動數據：9.0 m³ 混凝土交貨體積\n修正：申報表 90.0 → 9.0 m³，保留原始送貨單與修正紀錄。\n查證交接：原始送貨單、修正後申報表、差異說明（含權責人）。\n重試次數：${state.mistakes}\n\n此為教育遊戲的學習紀錄，不是正式證書、碳排放計算或查證結論。\nDEMO-001與收料狀態為遊戲假設。\n`;const u=URL.createObjectURL(new Blob([data],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='小綠碳盤查_學習紀錄.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);toast('學習紀錄已準備下載。');}
function confirmReset(){openDialog(`<div class="eyebrow">重新練習</div><h2 id="dialogTitle">開始新一輪任務？</h2><p class="sub">會清除這個瀏覽器儲存的遊戲進度。已下載的學習紀錄會保留。</p><div class="actions"><button class="secondary" id="cancelReset">取消</button><button class="primary" id="reset">重新開始</button></div>`);$('#cancelReset').onclick=closeDialog;$('#reset').onclick=()=>{state={done:0,mistakes:0,started:Date.now(),finished:null};save();update();target=[-1,0,4.7];closeDialog();toast('新任務開始！前往材料進場區。');};}
$('#help').onclick=()=>{openDialog(`<div class="eyebrow">HOW TO PLAY</div><h2 id="dialogTitle">點一個地標，就能開始。</h2><p class="sub">依序完成四個工地任務。不計時、不扣分，答錯會提供提示。</p><div class="result-list">🖱 點選地標或任務卡：開啟任務。<br>↔ 拖曳空白處：旋轉 3D 工地。<br>＋ 滾輪或 ＋／− 按鈕：調整遠近。<br>⌂ 小屋按鈕：回到預設視角。<br>⌨ 鍵盤 1–4 開啟任務；左右鍵旋轉；Esc 關閉視窗。<br>📱 手機直接點任務卡，單指拖曳旋轉。</div><p class="sub" style="margin-top:18px">進度自動保存在此瀏覽器。遊戲可離線使用，不會上傳你的作答。<br>小綠是依既有橘色安全帽與背心設定製作的幾何 3D 角色。<br>案例數值沿用影片的 9.0 m³；其他情境設定為教學模擬。</p><div class="actions"><button class="secondary" id="clearHelp">重設進度</button><button class="primary" id="startHelp">開始探索 →</button></div>`);$('#startHelp').onclick=closeDialog;$('#clearHelp').onclick=confirmReset;};
tasks.forEach((t,i)=>{const b=document.createElement('button');b.className='pin';b.onclick=()=>visit(i);b.setAttribute('aria-label',`${i+1} ${t.place}：${t.name}`);$('#pins').append(b);});update();

// Minimal 3D engine. Geometry is lit in world space and rendered with a depth buffer.
const canvas=$('#world');const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
let yaw=.68,pitch=.71,zoom=22, vp, width=0,height=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function setZoom(d){zoom=Math.max(16,Math.min(31,zoom+d));}
$('#left').onclick=()=>yaw-=.22;$('#right').onclick=()=>yaw+=.22;$('#zoomIn').onclick=()=>setZoom(-1.5);$('#zoomOut').onclick=()=>setZoom(1.5);$('#home').onclick=()=>{yaw=.68;pitch=.71;zoom=22;};
const sub=(a,b)=>a.map((x,i)=>x-b[i]), norm=a=>{let d=Math.hypot(...a);return a.map(x=>x/d);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
function mul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function look(eye,at){let z=norm(sub(eye,at)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);}
const rgb=h=>{let n=parseInt(h.replace('#',''),16);return[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255];};
let verts=[], dynamicStart=0;function triangle(a,b,c,color){const n=norm(cross(sub(b,a),sub(c,a)));[a,b,c].forEach(v=>verts.push(...v,...n,...color));}
function box(x,y,z,w,h,d,color,rot=0){let c=rgb(color),co=Math.cos(rot),si=Math.sin(rot);let pts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(([a,b,k])=>[x+a*w/2*co+k*d/2*si,y+b*h/2,z-a*w/2*si+k*d/2*co]);[[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]].forEach(q=>{triangle(pts[q[0]],pts[q[1]],pts[q[2]],c);triangle(pts[q[0]],pts[q[2]],pts[q[3]],c);});}
function cylinder(x,y,z,r,h,color,n=12,axis='y',r2=r){let c=rgb(color),point=(a,up,rr)=>axis==='x'?[x+up,y+Math.cos(a)*rr,z+Math.sin(a)*rr]:[x+Math.cos(a)*rr,y+up,z+Math.sin(a)*rr];for(let i=0;i<n;i++){let a=i/n*Math.PI*2,b=(i+1)/n*Math.PI*2,p=point(a,-h/2,r),q=point(b,-h/2,r),s=point(a,h/2,r2),t=point(b,h/2,r2);triangle(p,s,t,c);triangle(p,t,q,c);triangle(point(0,h/2,0),t,s,c);triangle(point(0,-h/2,0),p,q,c);}}
function tree(x,z,size=1){cylinder(x,.6*size,z,.1*size,1.2*size,'#977a50',7);cylinder(x,1.5*size,z,.7*size,1.6*size,'#53805a',7,'y',.04);cylinder(x,2.15*size,z,.5*size,1.2*size,'#719a5f',7,'y',.02);}
function bush(x,z){cylinder(x,.4,z,.46,.8,'#769756',8,'y',.27);}
function building(x,z,w,d,h,color){box(x,h/2,z,w,h,d,color);box(x,h+.12,z,w+.25,.24,d+.25,'#f1ebd9');box(x,h+.31,z,w-.4,.14,d-.4,'#456657');for(let j=0;j<3;j++){let xx=x-w*.29+j*w*.29;box(xx,h*.55,z+d/2+.018,w*.22,h*.36,.06,'#548b8a');box(xx,h*.55,z+d/2+.056,.05,h*.38,.03,'#dbe3cf');}box(x+w/2+.02,h*.5,z,.04,h*.55,d*.65,'#4f8080');box(x,h*.14,z+d/2+.2,w+.4,.2,.5,'#e6e5cf');}
function model(){
 box(0,-.8,0,21,1.15,17,'#b0bf91');box(0,-.23,0,21.2,.16,17.2,'#d5dfb4');box(0,-.07,0,20.8,.18,16.8,'#a6bb83');
 box(0,.04,1.9,19.8,.1,2.3,'#7f9583');box(0,.045,-2.25,2.3,.11,10.5,'#7f9583');
 for(let x=-9;x<10;x+=1.65)box(x,.11,1.9,.75,.012,.08,'#e4e5bf');for(let z=-6;z<1;z+=1.6)box(0,.12,z,.08,.01,.7,'#e4e5bf');
 for(let x=-9;x<=9;x+=.68){box(x,.12,3.15,.42,.12,.18,x%1.36<.68?'#d7d7b7':'#f3ecb9');}
 box(-5,.08,-4.5,6.3,.2,4.8,'#d3d4b6');building(-5,-4.7,4.8,2.5,2.05,'#efe9d6');
 box(-5,1.72,-3.41,3.6,.48,.08,'#2d765d');box(-6.7,.54,-3.08,.35,1,.2,'#577f59');bush(-7.5,-3);
 box(4.7,.1,-4.7,6.5,.21,4.9,'#d0d3b5');building(4.8,-4.8,4.3,2.8,2.6,'#e6dcc1');
 // Solar modules on the verification office roof.
 for(let j=0;j<4;j++){box(3.5+j*.82,2.99,-4.8,.7,.13,1.7,'#294f59',0);for(let k=0;k<3;k++)box(3.5+j*.82,3.062,-5.3+k*.5,.68,.01,.025,'#7fadb0');}
 box(5.2,.1,5,6.2,.18,4,'#c8d4ab');for(let x of[3,7.2])for(let z of[3.9,6.1])cylinder(x,1.14,z,.055,2.2,'#788f63',7);box(5.1,2.3,5,4.8,.15,2.9,'#e7c75e');box(5.1,1.14,5.5,3,.15,.8,'#bda97b');for(let x of[4,6])box(x,.57,5.5,.13,1.1,.45,'#6b7d5b');
 for(let x of[4.2,5.1,6])box(x,1.26,5.5,.55,.065,.5,'#f9f3dd');
 // Concrete mixer, oriented along the road.
 box(-5.1,.67,4.7,3.6,.3,1.45,'#425b50');box(-3.7,1.23,4.7,1.05,1.05,1.5,'#e9bc47');box(-3.14,1.38,4.7,.04,.5,1.18,'#548a8c');box(-3.7,1.42,5.46,.62,.46,.03,'#538487');box(-3.7,1.42,3.94,.62,.46,.03,'#538487');box(-3.13,.8,4.7,.1,.2,1.6,'#e6e5cd');
 cylinder(-5.35,1.37,4.7,.75,1.7,'#eee9d4',14,'x',.48);cylinder(-5.15,1.37,4.7,.73,.25,'#dfad46',14,'x',.68);box(-6.65,.97,4.7,.7,.12,.4,'#a8afa0',-.18);
 for(let x of[-6,-4,-3.5])for(let z of[3.93,5.47]){cylinder(x,.55,z,.39,.18,'#364c43',12,'y');box(x,.5,z,.53,.59,.24,'#354941');cylinder(x,.54,z,.14,.63,'#b7bda3',10,'x');}
 // Small unfinished structure and tower crane.
 box(7.9,.2,-.25,2.4,.35,2.4,'#d1cbb0');for(let x of[7,8.8])for(let z of[-1.1,.7])box(x,1.35,z,.18,2.5,.18,'#c3be9e');box(7.9,2.55,-.2,2.5,.2,2.3,'#d6d0b5');
 const cx=8.9,cz=-1.8;box(cx,2.1,cz,.24,4.2,.25,'#d8a742');for(let y=.3;y<4;y+=.55){box(cx,y,cz,.7,.085,.5,'#d8a742');}box(7.2,4.35,cz,5.2,.18,.27,'#dfb34e');box(cx,4.65,cz,.7,.65,.7,'#e9c257');box(7.3,3.66,cz,.04,1.3,.04,'#546858');box(7.3,3,cz,.18,.17,.18,'#68765c');
 // Materials, planting, safety cones, fence and site lighting.
 for(let j=0;j<3;j++){box(-8.6,.16+j*.2,5.4,1.15,.16,1.2,'#b89c6b');for(let k=0;k<3;k++)box(-8.98+k*.36,.29+j*.2,5.4,.3,.11,1,'#d4c7a3');}
 for(let [x,z] of[[-2.3,3.6],[-2.3,5.8],[2,3.3],[7.8,3.1],[-7.1,3.4]]){box(x,.1,z,.4,.12,.4,'#536854');cylinder(x,.35,z,.16,.5,'#df9246',8,'y',.03);cylinder(x,.38,z,.108,.095,'#f0edcc',8,'y',.085);}
 for(let x=-9;x<=9;x+=1.4){box(x,.46,-7.5,.07,.9,.07,'#698967');}box(0,.78,-7.5,18.8,.07,.07,'#6c8a61');box(0,.35,-7.5,18.8,.07,.07,'#6c8a61');
 for(let [x,z,s] of[[-9,-6,1.1],[-9,-2,.9],[-8,7,1.1],[-4,7.1,.75],[.5,6.5,.85],[9,6.8,1.15],[9.5,-6.6,.8],[1.4,-6.7,.85],[-2.2,-6.9,.7]])tree(x,z,s);
 for(let [x,z] of[[-8.3,-6],[-8.6,-5.5],[-7.6,7],[-3,7.2],[8.7,6.8],[7.9,-6.4],[2.2,-6.8]])bush(x,z);
 for(let x of[-1.6,1.7]){cylinder(x,1.38,-1.4,.045,2.75,'#557762',7);box(x,2.77,-1.4,.45,.1,.22,'#f1dfa0');}
 dynamicStart=verts.length;
}
function character(x,z,t){let y=.02+(reduced?0:Math.sin(t*2)*.025);box(x-.15,y+.23,z,.21,.42,.23,'#777b70');box(x+.15,y+.23,z,.21,.42,.23,'#777b70');box(x-.15,y+.07,z+.07,.24,.12,.36,'#324a40');box(x+.15,y+.07,z+.07,.24,.12,.36,'#324a40');box(x,y+.66,z,.61,.55,.36,'#ed9c42');box(x,y+.63,z+.192,.62,.075,.025,'#ede8a4');box(x-.24,y+.77,z+.19,.065,.33,.03,'#eee6a7');box(x+.24,y+.77,z+.19,.065,.33,.03,'#eee6a7');box(x-.39,y+.65,z,.17,.5,.21,'#ecebdb');box(x+.39,y+.65,z,.17,.5,.21,'#ecebdb');box(x,y+1.14,z,.53,.49,.45,'#eec79f');box(x,y+1.43,z,.59,.17,.5,'#e99736');box(x,y+1.36,z+.04,.72,.07,.66,'#f3ad40');box(x-.12,y+1.15,z+.235,.052,.067,.03,'#334b3d');box(x+.12,y+1.15,z+.235,.052,.067,.03,'#334b3d');box(x,y+1.02,z+.236,.09,.03,.025,'#a96d48');}
function marker(x,z,t,i){let c=i<state.done?'#659452':i===state.done?'#efc345':'#a3b391';cylinder(x,.025,z,1,.035,c,32);cylinder(x,.045,z,.78,.04,'#c9d6aa',32);if(i===state.done){let y=2.5+(reduced?0:Math.sin(t*2.5)*.12);cylinder(x,y,z,.18,.35,'#edbb44',4,'y',.02);}}
if(gl){
 const vertex=`attribute vec3 aPos;attribute vec3 aNormal;attribute vec3 aColor;uniform mat4 uVP;varying vec3 vColor;varying float vLight;void main(){gl_Position=uVP*vec4(aPos,1.0);vColor=aColor;vLight=.57+.43*max(dot(normalize(aNormal),normalize(vec3(-.6,1.0,.5))),0.0);}`;
 const fragment=`precision mediump float;varying vec3 vColor;varying float vLight;void main(){gl_FragColor=vec4(vColor*vLight,1.0);}`;
 function shader(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);['aPos','aNormal','aColor'].forEach((n,i)=>{let a=gl.getAttribLocation(program,n);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,36,i*12);});let uVP=gl.getUniformLocation(program,'uVP');gl.enable(gl.DEPTH_TEST);gl.clearColor(.914,.941,.871,1);model();const base=new Float32Array(verts);
 let pointer=null, last=0;canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(pointer){yaw+=(e.clientX-pointer.x)*.006;pitch=Math.max(.35,Math.min(1.15,pitch+(e.clientY-pointer.y)*.004));pointer={x:e.clientX,y:e.clientY};}});canvas.addEventListener('pointerup',()=>pointer=null);canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(e.deltaY*.015);},{passive:false});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#fallback').hidden=false;});canvas.addEventListener('webglcontextrestored',()=>location.reload());
 function frame(ms){const t=ms/1000,dt=Math.min((ms-last)/1000,.06);last=ms;width=canvas.clientWidth;height=canvas.clientHeight;const ratio=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(width*ratio)||canvas.height!==Math.round(height*ratio)){canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);gl.viewport(0,0,canvas.width,canvas.height);}const aspect=width/height,mobile=width<620;const viewSize=mobile?zoom*2.4:zoom;const eye=[Math.sin(yaw)*24*Math.cos(pitch),24*Math.sin(pitch),Math.cos(yaw)*24*Math.cos(pitch)];let shift=mobile?0:width<1000?1:1.3;vp=mul(ortho(-viewSize*aspect/2+shift,viewSize*aspect/2+shift,-viewSize/2+(mobile?-1.8:1.3),viewSize/2+(mobile?-1.8:1.3),.1,90),look(eye,[0,0,0]));gl.uniformMatrix4fv(uVP,false,vp);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
 verts=[];avatar[0]+=(target[0]-avatar[0])*Math.min(1,dt*2);avatar[2]+=(target[2]-avatar[2])*Math.min(1,dt*2);character(avatar[0],avatar[2],t);tasks.forEach((s,i)=>marker(s.pos[0],s.pos[2]+1,t,i));const dyn=new Float32Array(verts);const all=new Float32Array(base.length+dyn.length);all.set(base);all.set(dyn,base.length);gl.bufferData(gl.ARRAY_BUFFER,all,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,all.length/9);
 $$('.pin').forEach((el,i)=>{const p=tasks[i].pos;let v=[p[0],p[1]+.65,p[2],1],r=[0,0,0,0];for(let j=0;j<4;j++)for(let k=0;k<4;k++)r[j]+=vp[k*4+j]*v[k];el.style.left=(r[0]/r[3]+1)*width/2+'px';el.style.top=(1-r[1]/r[3])*height/2+'px';});requestAnimationFrame(frame);
 }requestAnimationFrame(frame);
}else{$('#fallback').hidden=false;$('#pins').style.display='none';}
